version: 0.0
os: linux
files:
  - source: /install.txt
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: ./scripts/before-install.sh
      timeout: 200
      runas: root
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 300


